### ISSUE TITLE
error: too many initializers

### ISSUE THREAD

**Issue by TheComputerGenie** [OWOWORLD/OWO#1]
https://github.com/OWOWORLD/OWO/blob/7b29e2d604ba9bb9891ec21d57fcb8afb28b6931/src/net.cpp#L1141-L1143

Should be:
`static const char *strDNSSeed[][2] = {"18.219.96.7", "18.216.137.177","18.218.187.48"};`

**Comment by NitBlockchain** [comment]
thanks for bringing this to our attention, this has been resolved
