### ISSUE TITLE
qmake broken

### ISSUE THREAD

**Issue by TheComputerGenie** [OWOWORLD/OWO#2]
> RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'res/icons/OWO-80.png'
> RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'res/icons/OWO-16.png'
> RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'res/icons/OWO-80.png'
> RCC: Error in 'src/qt/bitcoin.qrc': Cannot find file 'res/icons/OWO-16.png'

seems self-explanatory

**Comment by NitBlockchain** [comment]
resolved

**Comment by TheComputerGenie** [comment]
Yeah, no...

owo-80.png != OWO-80.png
owo-16.png != OWO-16.png
